services:
  subscriptions:
    container_name: subscriptions-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      GO_ENV: production
    ports:
      - 8080:8080
    env_file:
      - .env
    networks:
      - backend_fuse-network
networks:
  backend_fuse-network:
    external: true
